import Stripe from 'stripe';
import { MOCK_DATE } from '@/__tests__/constants/mock-basic';

export const mockStripeClientSecret = 'pi_1234567890';
export const mockStripeName = 'jane doe';
export const mockStripeEmail = 'jane@example.com';
export const mockStripeEmailRecipient = 'john@example.com';
export const mockStripeCustomerId = 'cus_1234567890';
export const mockStripeSubscriptionId = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13';
export const mockStipePaymentMethodId = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15';

export const MOCK_STRIPE_INVOICE_ID = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bdyy0a16';
export const MOCK_STRIPE_PAYMENT_INTENT_ID = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bdyy0a17';

export const mockStripAddress = {
  city: 'Miami',
  country: 'United States of America',
  line1: '123 Main St',
  line2: 'Apt 123',
  postal_code: '33123',
  state: 'Florida',
};
export const mockStripeApplication: Stripe.Application = {
  id: '315sat3t1141',
  name: mockStripeName,
  object: 'application',
};

export const mockAutomaticPayments: Stripe.PaymentIntent.AutomaticPaymentMethods = {
  allow_redirects: 'never',
  enabled: false,
};
export const mockStripeInvoiceId = 'in_1234567890';
export const mockStripeAccountId = 'acct_1234567890';

export const mockStripeProcessingCard: Stripe.PaymentIntent.Processing.Card = {
  customer_notification: {
    approval_requested: false,
    completes_at: null,
  },
};

export const mockStripePaymentProcessing: Stripe.PaymentIntent.Processing = {
  type: 'card',
  card: mockStripeProcessingCard,
};

export const mockStripeAccount: Stripe.Account = {
  id: mockStripeAccountId,
  object: 'account',
  business_profile: {
    annual_revenue: null,
    estimated_worker_count: null,
    mcc: null,
    name: mockStripeName,
    product_description: null,
    support_address: null,
    support_email: mockStripeEmail,
    support_phone: null,
    support_url: null,
    url: null,
  },
  business_type: 'individual',
  capabilities: {
    card_payments: 'active',
    transfers: 'active',
  },
  charges_enabled: true,
  company: {
    address: mockStripAddress,
    directors_provided: false,
    executives_provided: false,
    name: mockStripeName,
    owners_provided: false,
    ownership_declaration: null,
    phone: null,
    structure: undefined,
    tax_id_provided: false,
    verification: { document: { back: null, details: null, details_code: null, front: null } },
  },
  controller: {
    fees: { payer: 'account' },
    is_controller: false,
    losses: { payments: 'stripe' },
    requirement_collection: 'stripe',
    stripe_dashboard: { type: 'full' },
    type: 'application',
  },
  country: 'US',
  created: MOCK_DATE.getTime(),
  default_currency: 'usd',
  details_submitted: true,
  email: mockStripeEmail,
  external_accounts: {
    object: 'list',
    data: [],
    has_more: false,
    url: '/v1/accounts/acct_1234567890/external_accounts',
  },
  future_requirements: {
    alternatives: [],
    current_deadline: null,
    currently_due: [],
    disabled_reason: null,
    errors: [],
    eventually_due: [],
    past_due: [],
    pending_verification: [],
  },
  metadata: {},
  payouts_enabled: true,
  requirements: {
    alternatives: [],
    current_deadline: null,
    currently_due: [],
    disabled_reason: null,
    errors: [],
    eventually_due: [],
    past_due: [],
    pending_verification: [],
  },
  settings: {
    bacs_debit_payments: { display_name: null, service_user_number: null },
    branding: { icon: null, logo: null, primary_color: null, secondary_color: null },
    card_issuing: { tos_acceptance: { date: null, ip: null } },
    card_payments: {
      decline_on: { avs_failure: false, cvc_failure: false },
      statement_descriptor_prefix: null,
      statement_descriptor_prefix_kana: null,
      statement_descriptor_prefix_kanji: null,
    },
    dashboard: { display_name: mockStripeName, timezone: 'America/New_York' },
    invoices: { default_account_tax_ids: null },
    payments: {
      statement_descriptor: '',
      statement_descriptor_kana: null,
      statement_descriptor_kanji: null,
      statement_descriptor_prefix_kana: null,
      statement_descriptor_prefix_kanji: null,
    },
    payouts: {
      debit_negative_balances: false,
      schedule: { delay_days: 2, interval: 'daily' },
      statement_descriptor: null,
    },
    sepa_debit_payments: {},
    treasury: { tos_acceptance: { date: null, ip: null } },
  },
  tos_acceptance: {
    date: MOCK_DATE.getTime(),
    ip: '127.0.0.1',
    user_agent: undefined,
  },
  type: 'standard',
};
export const mockStripeInvoiceSettings: Stripe.Customer.InvoiceSettings = {
  custom_fields: null,
  default_payment_method: 'pm_1234567890',
  footer: 'Footer text',
  rendering_options: null,
};

export const mockStripCustomer: Stripe.Customer = {
  shipping: null,
  address: mockStripAddress,
  balance: 1525,
  cash_balance: {
    object: 'cash_balance',
    available: {
      example: 1234567890,
    },
    customer: mockStripeCustomerId,
    livemode: false,
    settings: {
      reconciliation_mode: 'automatic',
      using_merchant_default: true,
    },
  },
  created: MOCK_DATE.getTime(),
  default_source: 'default_payment_source',
  description: 'test stripe customer',
  email: mockStripeEmail,
  id: mockStripeCustomerId,
  invoice_settings: mockStripeInvoiceSettings,
  livemode: false,
  metadata: {},
  object: 'customer',
};

export const mockStripeInvoice: Stripe.Invoice = {
  automatically_finalizes_at: 0,
  account_country: 'US',
  account_name: mockStripeName,
  account_tax_ids: null,
  amount_due: 1000,
  amount_paid: 1000,
  amount_remaining: 0,
  amount_shipping: 0,
  application: null,
  application_fee_amount: null,
  attempt_count: 1,
  attempted: true,
  auto_advance: false,
  automatic_tax: { enabled: false, liability: null, status: null, disabled_reason: null },
  billing_reason: 'subscription_create',
  charge: null,
  collection_method: 'charge_automatically',
  created: MOCK_DATE.getTime(),
  currency: 'usd',
  custom_fields: null,
  customer: mockStripeCustomerId,
  customer_address: null,
  customer_email: mockStripeEmail,
  customer_name: mockStripeName,
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: 'none',
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  discounts: [],
  due_date: null,
  effective_at: MOCK_DATE.getTime(),
  ending_balance: 0,
  footer: null,
  from_invoice: null,
  hosted_invoice_url: 'https://invoice.stripe.com/i/test',
  id: mockStripeInvoiceId,
  invoice_pdf: 'https://pay.stripe.com/invoice/test/pdf',
  issuer: { type: 'self' },
  last_finalization_error: null,
  latest_revision: null,
  lines: {
    object: 'list',
    data: [],
    has_more: false,
    url: '/v1/invoices/in_1234567890/lines',
  },
  livemode: false,
  metadata: {},
  next_payment_attempt: null,
  number: 'DRAFT-1001',
  on_behalf_of: null,
  paid: true,
  paid_out_of_band: false,
  payment_intent: null,
  payment_settings: {
    default_mandate: null,
    payment_method_options: null,
    payment_method_types: null,
  },
  period_end: MOCK_DATE.getTime(),
  period_start: MOCK_DATE.getTime(),
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  object: 'invoice',
  quote: null,
  receipt_number: null,
  rendering: null,
  shipping_cost: null,
  shipping_details: null,
  starting_balance: 0,
  statement_descriptor: null,
  status: 'paid',
  status_transitions: {
    finalized_at: MOCK_DATE.getTime(),
    marked_uncollectible_at: null,
    paid_at: MOCK_DATE.getTime(),
    voided_at: null,
  },
  subscription: mockStripeSubscriptionId,
  subscription_details: { metadata: null },
  subtotal: 1000,
  subtotal_excluding_tax: null,
  tax: null,
  test_clock: null,
  total: 1000,
  total_discount_amounts: [],
  total_excluding_tax: null,
  total_pretax_credit_amounts: null,
  total_tax_amounts: [],
  transfer_data: null,
  webhooks_delivered_at: MOCK_DATE.getTime(),
};

export const mockStripeChargeId = 'ch_1234567890';

export const mockStripeCharge: Stripe.Charge = {
  id: mockStripeChargeId,
  object: 'charge',
  amount: 1000,
  amount_captured: 1000,
  amount_refunded: 0,
  application: null,
  application_fee: null,
  application_fee_amount: null,
  balance_transaction: null,
  billing_details: {
    address: mockStripAddress,
    email: mockStripeEmail,
    name: mockStripeName,
    phone: null,
  },
  calculated_statement_descriptor: null,
  captured: true,
  created: MOCK_DATE.getTime(),
  currency: 'usd',
  customer: mockStripeCustomerId,
  description: null,
  disputed: false,
  failure_balance_transaction: null,
  failure_code: null,
  failure_message: null,
  fraud_details: {},
  invoice: mockStripeInvoiceId,
  livemode: false,
  metadata: {},
  on_behalf_of: null,
  outcome: null,
  paid: true,
  payment_intent: 'pi_1234567890',
  payment_method: mockStipePaymentMethodId,
  payment_method_details: {
    type: 'card',
    card: {
      amount_authorized: 1000,
      authorization_code: null,
      brand: 'visa',
      checks: {
        address_line1_check: 'pass',
        address_postal_code_check: 'pass',
        cvc_check: 'pass',
      },
      country: 'US',
      exp_month: 12,
      exp_year: 2030,
      extended_authorization: { status: 'disabled' },
      fingerprint: 'fingerprint_1234567890',
      funding: 'credit',
      incremental_authorization: { status: 'unavailable' },
      installments: null,
      last4: '4242',
      mandate: null,
      moto: null,
      multicapture: { status: 'unavailable' },
      network: 'visa',
      network_token: { used: false },
      network_transaction_id: null,
      overcapture: { maximum_amount_capturable: 1000, status: 'unavailable' },
      three_d_secure: null,
      wallet: null,
      regulated_status: null,
    },
  },
  radar_options: {},
  receipt_email: mockStripeEmail,
  receipt_number: null,
  receipt_url: 'https://pay.stripe.com/receipts/test',
  refunded: false,
  review: null,
  shipping: null,
  source: null,
  source_transfer: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: 'succeeded',
  transfer_data: null,
  transfer_group: null,
};

export const mockStripePaymentIntent: Stripe.PaymentIntent = {
  amount: 1000,
  amount_capturable: 1000,
  amount_received: 0,
  application: mockStripeApplication,
  application_fee_amount: 0,
  automatic_payment_methods: mockAutomaticPayments,
  canceled_at: null,
  cancellation_reason: null,
  capture_method: 'automatic',
  client_secret: mockStripeClientSecret,
  confirmation_method: 'automatic',
  created: 0,
  currency: '',
  customer: mockStripCustomer,
  description: 'a mocked payment intent',
  id: 'pi_1234567890',
  invoice: mockStripeInvoice,
  last_payment_error: null,
  latest_charge: mockStripeCharge,
  livemode: false,
  metadata: {},
  next_action: null,
  object: 'payment_intent',
  on_behalf_of: mockStripeAccount,
  payment_method: mockStipePaymentMethodId,
  payment_method_configuration_details: null,
  payment_method_options: null,
  payment_method_types: ['card'],
  processing: mockStripePaymentProcessing,
  receipt_email: mockStripeEmailRecipient,
  review: null,
  setup_future_usage: null,
  shipping: null,
  source: mockStripeAccount,
  statement_descriptor: 'writers-bot',
  statement_descriptor_suffix: null,
  status: 'succeeded',
  transfer_data: {
    amount: 1525,
    destination: mockStripeAccount,
  },
  transfer_group: null,
};
